package com.example.localization

import com.example.model.AppLanguage

object AppStrings {
    fun get(key: String, language: AppLanguage): String {
        val map = if (language == AppLanguage.BENGALI) bengaliMap else englishMap
        return map[key] ?: englishMap[key] ?: key
    }

    private val englishMap = mapOf(
        "app_name" to "Ayush Textile",
        "home" to "Home",
        "collection" to "Collection",
        "add" to "Add",
        "settings" to "Settings",
        "search_placeholder" to "Search products...",
        "search_by_name_code" to "Search by name, code or category...",
        "total_products" to "Total Products",
        "total_categories" to "Total Categories",
        "all" to "All",
        "no_products_title" to "No products added yet",
        "no_products_subtitle" to "Start building your fabric catalog by tapping Add Product",
        "no_search_results" to "No fabrics found matching your search",
        "add_product" to "Add Product",
        "edit_product" to "Edit Product",
        "product_details" to "Product Details",
        "product_name" to "Product Name",
        "product_code" to "Product Code / SKU",
        "price" to "Price",
        "category" to "Category",
        "description" to "Short Description",
        "notes" to "Notes",
        "date_added" to "Date Added",
        "last_updated" to "Last Updated",
        "auto_generate_code" to "Auto Generate Code",
        "take_photo" to "Take Photo",
        "choose_gallery" to "Choose from Gallery",
        "use_sample_pattern" to "Use Sample Pattern",
        "change_photo" to "Change Photo",
        "remove_photo" to "Remove Photo",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "edit" to "Edit",
        "share" to "Share",
        "confirm_delete_title" to "Delete Product",
        "confirm_delete_msg" to "Are you sure you want to delete this product?",
        "sort_by" to "Sort by",
        "sort_newest" to "Newest First",
        "sort_oldest" to "Oldest First",
        "sort_name_asc" to "Name A-Z",
        "sort_name_desc" to "Name Z-A",
        "sort_price_low_high" to "Price: Low to High",
        "sort_price_high_low" to "Price: High to Low",
        "appearance" to "Appearance",
        "theme_mode" to "Theme Mode",
        "theme_light" to "Light Mode",
        "theme_dark" to "Dark Mode",
        "theme_system" to "System Default",
        "adaptive_theme" to "Adaptive Dynamic Color (Android 12+)",
        "adaptive_theme_desc" to "Adapt colors automatically from system wallpaper",
        "camera_permission_required" to "Camera permission is required to take photos",
        "accent_color" to "Accent Color",
        "language" to "Language",
        "category_management" to "Manage Categories",
        "add_category" to "Add Category",
        "category_name" to "Category Name",
        "edit_category" to "Edit Category",
        "delete_category" to "Delete Category",
        "confirm_delete_category" to "Are you sure you want to delete this category? Products in it will be reassigned to 'Other'.",
        "backup_restore" to "Backup & Restore",
        "export_backup" to "Export Backup JSON",
        "import_restore" to "Import & Restore JSON",
        "backup_success" to "Backup generated successfully!",
        "restore_success" to "Database restored successfully!",
        "confirm_restore_title" to "Restore Database",
        "confirm_restore_msg" to "Restoring will replace current product data. Do you wish to continue?",
        "about" to "About App",
        "about_desc" to "My Fabric Collection - Simple offline fabric and product catalog management for shop owners.",
        "err_name_required" to "Please enter a product name.",
        "err_price_invalid" to "Please enter a valid numeric price.",
        "err_code_duplicate" to "Product code already exists. Please use a unique code.",
        "share_product_template" to "Product Name: %1\$s\nCode: %2\$s\nPrice: %3\$s\nCategory: %4\$s",
        "cat_cotton" to "Cotton",
        "cat_silk" to "Silk",
        "cat_georgette" to "Georgette",
        "cat_linen" to "Linen",
        "cat_printed" to "Printed",
        "cat_dress_material" to "Dress Material",
        "cat_nighty_fabric" to "Nighty Fabric",
        "cat_other" to "Other"
    )

    private val bengaliMap = mapOf(
        "app_name" to "আয়ুষ টেক্সটাইল",
        "home" to "হোম",
        "collection" to "কালেকশন",
        "add" to "যোগ করুন",
        "settings" to "সেটিংস",
        "search_placeholder" to "কাপড় খুঁজুন...",
        "search_by_name_code" to "নাম, কোড বা ক্যাটাগরি দিয়ে খুঁজুন...",
        "total_products" to "মোট কাপড়",
        "total_categories" to "মোট ক্যাটাগরি",
        "all" to "সবগুলো",
        "no_products_title" to "এখনও কোনো পণ্য যোগ করা হয়নি",
        "no_products_subtitle" to "'পণ্য যোগ করুন' বোতামে চাপ দিয়ে কাপড়ের ক্যাটালগ তৈরি করুন",
        "no_search_results" to "আপনার অনুসন্ধানের সাথে মিল থাকা কোনো কাপড় পাওয়া যায়নি",
        "add_product" to "কাপড় যোগ করুন",
        "edit_product" to "কাপড় সম্পাদনা করুন",
        "product_details" to "পণ্যের বিবরণ",
        "product_name" to "কাপড়ের নাম",
        "product_code" to "প্রোডাক্ট কোড / SKU",
        "price" to "দাম",
        "category" to "ক্যাটাগরি",
        "description" to "সংক্ষিপ্ত বিবরণ",
        "notes" to "নোট",
        "date_added" to "যোগ করার তারিখ",
        "last_updated" to "সর্বশেষ আপডেট",
        "auto_generate_code" to "স্বয়ংক্রিয় কোড তৈরি করুন",
        "take_photo" to "ছবি তুলুন",
        "choose_gallery" to "গ্যালারি থেকে বাছুন",
        "use_sample_pattern" to "নমুনা ফেব্রিক ব্যবহার করুন",
        "change_photo" to "ছবি পরিবর্তন করুন",
        "remove_photo" to "ছবি মুছে ফেলুন",
        "save" to "সংরক্ষণ করুন",
        "cancel" to "বাতিল",
        "delete" to "মুছে ফেলুন",
        "edit" to "সম্পাদনা",
        "share" to "শেয়ার করুন",
        "confirm_delete_title" to "কাপড় মুছে ফেলুন",
        "confirm_delete_msg" to "আপনি কি এই পণ্যটি মুছে ফেলতে চান?",
        "sort_by" to "সাজান",
        "sort_newest" to "সবচেয়ে নতুন আগে",
        "sort_oldest" to "সবচেয়ে পুরোনো আগে",
        "sort_name_asc" to "নাম (A থেকে Z)",
        "sort_name_desc" to "নাম (Z থেকে A)",
        "sort_price_low_high" to "দাম: কম থেকে বেশি",
        "sort_price_high_low" to "দাম: বেশি থেকে কম",
        "appearance" to "থিম ও রূপরেখা",
        "theme_mode" to "থিম মোড",
        "theme_light" to "লাইটিং মোড",
        "theme_dark" to "ডার্ক মোড",
        "theme_system" to "সিস্টেম ডিফল্ট",
        "adaptive_theme" to "অ্যাডাপ্টিভ ডায়নামিক কালার (Android 12+)",
        "adaptive_theme_desc" to "সিস্টেম ওয়ালপেপারের রঙের সাথে মিলিয়ে স্বয়ংক্রিয়ভাবে রঙ পরিবর্তন করবে",
        "camera_permission_required" to "ছবি তোলার জন্য ক্যামেরার অনুমতি প্রয়োজন",
        "accent_color" to "মূল রঙ",
        "language" to "ভাষা",
        "category_management" to "ক্যাটাগরি ব্যবস্থাপনা",
        "add_category" to "ক্যাটাগরি যোগ করুন",
        "category_name" to "ক্যাটাগরির নাম",
        "edit_category" to "ক্যাটাগরি সম্পাদনা",
        "delete_category" to "ক্যাটাগরি মুছে ফেলুন",
        "confirm_delete_category" to "আপনি কি এই ক্যাটাগরি মুছে ফেলতে চান? পণ্যগুলো 'অন্যান্য' ক্যাটাগরিতে স্থানান্তরিত হবে।",
        "backup_restore" to "ব্যাকআপ ও রিস্টোর",
        "export_backup" to "ব্যাকআপ ফাইল সংরক্ষণ করুন (JSON)",
        "import_restore" to "ব্যাকআপ রিস্টোর করুন (JSON)",
        "backup_success" to "ব্যাকআপ সফলভাবে তৈরি হয়েছে!",
        "restore_success" to "ডাটাবেস সফলভাবে রিস্টোর হয়েছে!",
        "confirm_restore_title" to "ডাটাবেস রিস্টোর করুন",
        "confirm_restore_msg" to "রিস্টোর করলে বর্তমান সমস্ত পণ্যের তথ্য প্রতিস্থাপিত হবে। আপনি কি চালিয়ে যেতে চান?",
        "about" to "অ্যাপ সম্পর্কে",
        "about_desc" to "মাই ফেব্রিক কালেকশন - দোকানদারদের জন্য অতি সহজ ও দ্রুত অফলাইন কাপড় ক্যাটালগ ব্যবস্থাপনা অ্যাপ।",
        "err_name_required" to "দয়া করে পণ্যের নাম লিখুন।",
        "err_price_invalid" to "দয়া করে সঠিক দাম লিখুন।",
        "err_code_duplicate" to "এই কোডটি ইতিমধ্যে ব্যবহৃত হয়েছে। দয়া করে অনন্য কোড লিখুন।",
        "share_product_template" to "কাপড়ের নাম: %1\$s\nকোড: %2\$s\nদাম: %3\$s\nক্যাটাগরি: %4\$s",
        "cat_cotton" to "সুতি (Cotton)",
        "cat_silk" to "রেশম (Silk)",
        "cat_georgette" to "জর্জজেট (Georgette)",
        "cat_linen" to "লিনেন (Linen)",
        "cat_printed" to "প্রিন্টেড (Printed)",
        "cat_dress_material" to "ড্রেস মেটেরিয়াল (Dress Material)",
        "cat_nighty_fabric" to "নাইটি ফেব্রিক (Nighty Fabric)",
        "cat_other" to "অন্যান্য (Other)"
    )
}
